# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1552569909);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1552570029);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1489422932);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1489423172);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1489423052);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1552570149);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1489422813);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1552570124748");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1552572028748");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1552569866262");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1552573466262");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160606113944");
user_pref("browser.slowStartup.averageTime", 9658);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20160606113944");
user_pref("browser.startup.homepage_override.mstone", "47.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\"]},\"seen\":[\"loop-button\",\"pocket-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"PanelUI-contents\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1489422877144");
user_pref("datareporting.sessions.current.activeTicks", 51);
user_pref("datareporting.sessions.current.firstPaint", 10592);
user_pref("datareporting.sessions.current.main", 3014);
user_pref("datareporting.sessions.current.sessionRestored", 10677);
user_pref("datareporting.sessions.current.startTime", "1552569781052");
user_pref("datareporting.sessions.current.totalTime", 324);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.prunedIndex", 2);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "unsupportedChannel");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"loop@mozilla.org\":{\"version\":\"1.3.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:47.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "47.0");
user_pref("extensions.lastPlatformVersion", "47.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1465217167000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.2\",\"st\":1465217168000},\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3.2\",\"st\":1465217168000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"47.0\",\"st\":1465217167000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20160606113944");
user_pref("gecko.mstone", "47.0");
user_pref("idle.lastDailyNotification", 1552570211);
user_pref("loop.copy.ticket", 12);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1552569868);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160606113944");
user_pref("media.gmp-manager.lastCheck", 1552569856);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1489423144);
user_pref("places.history.expiration.transient_current_max_pages", 42944);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1489423144);
user_pref("toolkit.startup.last_success", 1552569784);
user_pref("toolkit.telemetry.cachedClientID", "15e8dd45-f5f1-4b08-bb56-d5d913004bfe");
user_pref("toolkit.telemetry.previousBuildID", "20160606113944");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
